const AppConstants = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  FETCH_DATA_CANCELLED: 'FETCH_DATA_CANCELLED',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_SEARCH_SUCCESS: 'PRODUCT_SEARCH_SUCCESS',
  PRODUCT_SEARCH_ERROR: 'PRODUCT_SEARCH_ERROR',
  PRODUCT_SEARCH_CANCELLED: 'PRODUCT_SEARCH_CANCELLED',
  SORT_PRODUCTS: 'SORT_PRODUCTS',
  SORT_PRODUCTS_SUCCESS: 'SORT_PRODUCTS_SUCCESS',
  SORT_PRODUCTS_ERROR: 'SORT_PRODUCTS_ERROR',
  SORT_PRODUCTS_CANCELLED: 'SORT_PRODUCTS_CANCELLED'
};


export default AppConstants;